//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhoiLuongCongViecGiangVienNTU_62132937
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYGIANGVIENEntities2 : DbContext
    {
        public QUANLYGIANGVIENEntities2()
            : base("name=QUANLYGIANGVIENEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoMon> BoMon { get; set; }
        public virtual DbSet<ChucVu> ChucVu { get; set; }
        public virtual DbSet<DoAnTotNghiep> DoAnTotNghiep { get; set; }
        public virtual DbSet<GiangDay> GiangDay { get; set; }
        public virtual DbSet<GiaoVien> GiaoVien { get; set; }
        public virtual DbSet<GiaoVienNCKH> GiaoVienNCKH { get; set; }
        public virtual DbSet<GioChuan> GioChuan { get; set; }
        public virtual DbSet<HeDaoTao> HeDaoTao { get; set; }
        public virtual DbSet<HeSoLopDong> HeSoLopDong { get; set; }
        public virtual DbSet<HocBSNangCao> HocBSNangCao { get; set; }
        public virtual DbSet<HuongDanNCKH> HuongDanNCKH { get; set; }
        public virtual DbSet<LoaiMon> LoaiMon { get; set; }
        public virtual DbSet<Lop> Lop { get; set; }
        public virtual DbSet<MonHoc> MonHoc { get; set; }
        public virtual DbSet<QLPhongMay> QLPhongMay { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoan { get; set; }
    }
}
