//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhoiLuongCongViecGiangVienNTU_62132937
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoAnTotNghiep
    {
        public string MaGV { get; set; }
        public string MaLop { get; set; }
        public Nullable<int> SoDeTai { get; set; }
        public Nullable<int> SoDoAnPBien { get; set; }
        public Nullable<int> SoBuoiChamBai { get; set; }
        public string NamHoc { get; set; }
        public string GhiChu { get; set; }
        public int Ma { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
