//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhoiLuongCongViecGiangVienNTU_62132937
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeSoLopDong
    {
        public string MaHSLopDong { get; set; }
        public Nullable<int> Tu { get; set; }
        public Nullable<int> Den { get; set; }
        public double HeSo { get; set; }
        public string HinhThucDay { get; set; }
    }
}
